//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Game
    {
        public int Game_Id { get; set; }

        [Required(ErrorMessage = "This field is Required!")]
        public string Game_Name { get; set; }

        [Required(ErrorMessage = "This field is Required!")]
        public Nullable<double> Price { get; set; }

        public Nullable<int> Category_Id { get; set; }

        public Nullable<int> Developer_Id { get; set; }


        public string Game_Image { get; set; }

        [Required(ErrorMessage = "This field is Required!")]
        public string Description { get; set; }

        [Required(ErrorMessage = "This field is Required!")]
        public string RAM { get; set; }

        [Required(ErrorMessage = "This field is Required!")]
        public string VGA { get; set; }

        [Required(ErrorMessage = "This field is Required!")]
        public string Disk_Space { get; set; }

        [Required(ErrorMessage = "This field is Required!")]
        public string CPU { get; set; }

        public virtual Category Category { get; set; }
        public virtual Developer Developer { get; set; }
    }
}
