//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;

    public partial class OrderDetail
    {
        public int Order_Id { get; set; }
        public int Customer_Id { get; set; }
        public double Order_Amount { get; set; }
        public System.DateTime Order_Date { get; set; }

        public virtual User User { get; set; }
    }
}
